// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpHGzGPtTLAyT9OJtfP5c_4jUoYwzces',
    appId: '1:533039063859:web:7cba058f861b15ce3cd446',
    messagingSenderId: '533039063859',
    projectId: 'sharequestion-ed0ef',
    authDomain: 'sharequestion-ed0ef.firebaseapp.com',
    storageBucket: 'sharequestion-ed0ef.appspot.com',
    measurementId: 'G-TZKSVKV2JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACu8-tYLxH1cFdgJjJ0z291mcY_tp0wkM',
    appId: '1:533039063859:android:4c918a804cb777683cd446',
    messagingSenderId: '533039063859',
    projectId: 'sharequestion-ed0ef',
    storageBucket: 'sharequestion-ed0ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEZH4PuUeKntlsX6QVB2N2jrD_Ow-IzY',
    appId: '1:533039063859:ios:edd69fe294259dc13cd446',
    messagingSenderId: '533039063859',
    projectId: 'sharequestion-ed0ef',
    storageBucket: 'sharequestion-ed0ef.appspot.com',
    iosBundleId: 'com.example.shareQuestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrEZH4PuUeKntlsX6QVB2N2jrD_Ow-IzY',
    appId: '1:533039063859:ios:97a3084a8c1392ea3cd446',
    messagingSenderId: '533039063859',
    projectId: 'sharequestion-ed0ef',
    storageBucket: 'sharequestion-ed0ef.appspot.com',
    iosBundleId: 'com.example.shareQuestion.RunnerTests',
  );
}
