// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfiEVVk_YgqWOxDBBWFU5ULIOeDvbHpQE',
    appId: '1:1007608032854:web:b789164c3399e542bb15f7',
    messagingSenderId: '1007608032854',
    projectId: 'qshare-32165',
    authDomain: 'qshare-32165.firebaseapp.com',
    storageBucket: 'qshare-32165.appspot.com',
    measurementId: 'G-EQ9BZE8GXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNku4b9XWgE_86au4FGC9l-KVZ3PkeqL0',
    appId: '1:1007608032854:android:dd8a92badaeaa537bb15f7',
    messagingSenderId: '1007608032854',
    projectId: 'qshare-32165',
    storageBucket: 'qshare-32165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFQHeA1ubbxL9e2KMO6y9L_ZWbEtykbg4',
    appId: '1:1007608032854:ios:1e7a2e38bbfcf54bbb15f7',
    messagingSenderId: '1007608032854',
    projectId: 'qshare-32165',
    storageBucket: 'qshare-32165.appspot.com',
    androidClientId: '1007608032854-mvniqhbvdhe11n1qkkn38gc29jdfnc5c.apps.googleusercontent.com',
    iosClientId: '1007608032854-cki36gbiodqi7fj2seiloolhm3d4d5nm.apps.googleusercontent.com',
    iosBundleId: 'com.share.question',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFQHeA1ubbxL9e2KMO6y9L_ZWbEtykbg4',
    appId: '1:1007608032854:ios:5117144acdbdcd9abb15f7',
    messagingSenderId: '1007608032854',
    projectId: 'qshare-32165',
    storageBucket: 'qshare-32165.appspot.com',
    androidClientId: '1007608032854-mvniqhbvdhe11n1qkkn38gc29jdfnc5c.apps.googleusercontent.com',
    iosClientId: '1007608032854-elvjqe0n8g04p86qpnroburv2t9a55es.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareQuestion.RunnerTests',
  );
}
